<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="18" started-at="2021-06-27T07:29:40Z" finished-at="2021-06-27T07:29:40Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="18" started-at="2021-06-27T07:29:40Z" finished-at="2021-06-27T07:29:40Z">
      <class name="LHTTest">
        <test-method status="FAIL" signature="testMethod1()[pri:0, instance:LHTTest@6d1e7682]" name="testMethod1" duration-ms="4" started-at="2021-06-27T07:29:40Z" finished-at="2021-06-27T07:29:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[TEST]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: TEST
at LHTTest.testMethod1(LHTTest.java:7)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at TestNgLearning.main(TestNgLearning.java:10)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod1 -->
        <test-method status="PASS" signature="testMethod2()[pri:0, instance:LHTTest@6d1e7682]" name="testMethod2" duration-ms="0" started-at="2021-06-27T07:29:40Z" finished-at="2021-06-27T07:29:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod2 -->
      </class> <!-- LHTTest -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
